FROM node:18.20-alpine as builder

WORKDIR /home/node/app 

COPY web/package*.json ./ 

RUN npm i

COPY web .

RUN npm run build

FROM nginx as production-stage
COPY --from=builder /home/node/app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]