# Build stage
FROM golang:1.21-alpine as builder

WORKDIR /go/src/app

ENV GO111MODULE=on

COPY api ./

RUN go mod download
RUN go build main.go 

# Production stage
FROM golang:1.21-alpine as production-stage

COPY --from=builder /go/src/app/main ./ 

EXPOSE 8000 

CMD [ "./main" ]